package com.buildgraph.prototype.agent;

import com.buildgraph.prototype.common.MockData;
import com.buildgraph.prototype.part.ToolCheckService;
import java.util.List;
import java.util.Map;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.server.ResponseStatusException;

public class LlmAgentRunner implements AgentRunner {
    private static final String AGENT_SUMMARY_SCHEMA_NAME = "buildgraph_agent_summary_text";
    private static final String SYSTEM_PROMPT = """
            당신은 BuildGraph AI의 하드웨어 컨설팅 Agent입니다.
            입력된 Agent 목적, RAG 근거, Tool 검증 결과만 사용해 한국어 summary를 작성하십시오.
            확인되지 않은 부품명, 가격, 성능 수치를 새로 지어내지 마십시오.
            사용자가 바로 이해할 수 있게 핵심 판단, 주의점, 다음 행동을 3~5문장으로 답하십시오.
            """;

    private final AgentTraceService agentTraceService;
    private final AgentRagRetrievalService agentRagRetrievalService;
    private final OpenAiResponsesClient openAiResponsesClient;
    private final ToolCheckService toolCheckService;
    private final LlmGenerationService llmGenerationService;
    private final AiProfileDefinition aiProfile;
    private final JdbcTemplate jdbcTemplate;

    public LlmAgentRunner(
            AgentTraceService agentTraceService,
            AgentRagRetrievalService agentRagRetrievalService,
            OpenAiResponsesClient openAiResponsesClient,
            ToolCheckService toolCheckService,
            LlmGenerationService llmGenerationService,
            AiProfileDefinition aiProfile,
            JdbcTemplate jdbcTemplate
    ) {
        this.agentTraceService = agentTraceService;
        this.agentRagRetrievalService = agentRagRetrievalService;
        this.openAiResponsesClient = openAiResponsesClient;
        this.toolCheckService = toolCheckService;
        this.llmGenerationService = llmGenerationService;
        this.aiProfile = aiProfile;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String sessionId, AgentSessionRoot root, AgentRunProfile profile) {
        List<AgentRagEvidenceDraft> evidenceSet = agentRagRetrievalService.retrieveEvidenceSet(root, profile);
        List<String> evidenceIds = evidenceSet.stream()
                .map(evidence -> agentTraceService.recordRagEvidence(sessionId, evidence))
                .toList();
        agentTraceService.advanceStatus(sessionId, AgentStatus.RAG_SEARCHED, "SYSTEM", "RAG evidence set retrieved for " + profile.purpose());

        List<AgentToolInvocationDraft> toolDrafts = toolInvocations(root, profile);
        List<String> toolInvocationIds = toolDrafts.stream()
                .map(draft -> agentTraceService.recordToolInvocation(sessionId, draft))
                .toList();
        agentTraceService.advanceStatus(sessionId, AgentStatus.TOOLS_CALLED, "SYSTEM", "tool invocations completed for " + profile.purpose());

        Long agentInternalId = agentInternalId(sessionId);
        try {
            LlmResponseResult llmResult = openAiResponsesClient.createSummaryResult(
                    SYSTEM_PROMPT,
                    userPrompt(root, profile, evidenceIds, evidenceSet, toolInvocationIds, toolDrafts)
            );
            String summary = llmResult.text();
            llmGenerationService.recordSuccess(
                    agentInternalId,
                    aiProfile,
                    profile.purpose().name(),
                    AGENT_SUMMARY_SCHEMA_NAME,
                    llmResult,
                    requestMetadata(root, evidenceIds, toolInvocationIds)
            );
            agentTraceService.updateSummary(sessionId, summary);
            agentTraceService.advanceStatus(sessionId, AgentStatus.SUMMARY_READY, "SYSTEM", "LLM summary generated by " + openAiResponsesClient.model());
            agentTraceService.advanceStatus(sessionId, AgentStatus.SUCCEEDED, "SYSTEM", "LLM agent run completed");
        } catch (RuntimeException error) {
            recordFailure(agentInternalId, profile, root, evidenceIds, toolInvocationIds, error);
            agentTraceService.updateSummary(sessionId, "LLM summary generation failed: " + safeReason(error));
            agentTraceService.advanceStatus(sessionId, AgentStatus.FALLBACK_READY, "SYSTEM", "LLM summary generation failed");
            agentTraceService.advanceStatus(sessionId, AgentStatus.FAILED, "SYSTEM", "LLM agent run failed");
        }
    }

    private static String userPrompt(
            AgentSessionRoot root,
            AgentRunProfile profile,
            List<String> evidenceIds,
            List<AgentRagEvidenceDraft> evidenceSet,
            List<String> toolInvocationIds,
            List<AgentToolInvocationDraft> toolDrafts
    ) {
        return AgentTraceService.json(MockData.map(
                "purpose", profile.purpose().name(),
                "summaryTarget", profile.summaryTarget(),
                "root", MockData.map(
                        "type", root.type().name(),
                        "id", root.publicId()
                ),
                "ragEvidenceSet", evidenceItems(evidenceIds, evidenceSet),
                "toolInvocations", toolItems(toolInvocationIds, toolDrafts),
                "outputInstruction", "Return only the customer-facing Korean summary text."
        ));
    }

    private static List<Map<String, Object>> evidenceItems(List<String> ids, List<AgentRagEvidenceDraft> drafts) {
        return java.util.stream.IntStream.range(0, drafts.size())
                .mapToObj(index -> {
                    AgentRagEvidenceDraft draft = drafts.get(index);
                    return MockData.map(
                            "id", ids.get(index),
                            "sourceId", draft.sourceId(),
                            "summary", draft.summary(),
                            "chunkText", draft.chunkText(),
                            "score", draft.score(),
                            "metadata", draft.metadata()
                    );
                })
                .toList();
    }

    private static List<Map<String, Object>> toolItems(List<String> ids, List<AgentToolInvocationDraft> drafts) {
        return java.util.stream.IntStream.range(0, drafts.size())
                .mapToObj(index -> {
                    AgentToolInvocationDraft draft = drafts.get(index);
                    return MockData.map(
                            "id", ids.get(index),
                            "toolName", draft.toolName(),
                            "status", draft.status().name(),
                            "confidence", draft.confidence().name(),
                            "summary", draft.summary(),
                            "requestPayload", draft.requestPayload(),
                            "resultPayload", draft.resultPayload()
                    );
                })
                .toList();
    }

    private static String safeReason(RuntimeException error) {
        if (error instanceof ResponseStatusException responseStatusException && responseStatusException.getReason() != null) {
            return responseStatusException.getReason();
        }
        String message = error.getMessage();
        return message == null || message.isBlank() ? error.getClass().getSimpleName() : message;
    }

    private Long agentInternalId(String sessionId) {
        return jdbcTemplate.queryForList("""
                        SELECT id
                        FROM agent_sessions
                        WHERE public_id = ?::uuid
                        """, sessionId)
                .stream()
                .findFirst()
                .map(row -> longValue(row, "id"))
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Agent session을 찾을 수 없습니다."));
    }

    private void recordFailure(
            Long agentInternalId,
            AgentRunProfile profile,
            AgentSessionRoot root,
            List<String> evidenceIds,
            List<String> toolInvocationIds,
            RuntimeException error
    ) {
        try {
            llmGenerationService.recordFailure(
                    agentInternalId,
                    aiProfile,
                    profile.purpose().name(),
                    AGENT_SUMMARY_SCHEMA_NAME,
                    false,
                    null,
                    errorCode(error),
                    safeReason(error),
                    requestMetadata(root, evidenceIds, toolInvocationIds)
            );
        } catch (RuntimeException ignored) {
            // Preserve the original Agent failure path even if telemetry recording fails.
        }
    }

    private static String errorCode(RuntimeException error) {
        if (error instanceof ResponseStatusException responseStatusException) {
            return "HTTP_" + responseStatusException.getStatusCode().value();
        }
        return error.getClass().getSimpleName();
    }

    private static Long longValue(Map<String, Object> row, String key) {
        Object value = row.get(key);
        if (value instanceof Number number) {
            return number.longValue();
        }
        if (value == null) {
            return null;
        }
        return Long.valueOf(value.toString());
    }

    private static Map<String, Object> requestMetadata(
            AgentSessionRoot root,
            List<String> evidenceIds,
            List<String> toolInvocationIds
    ) {
        return MockData.map(
                "rootType", root.type().name(),
                "rootId", root.publicId(),
                "ragEvidenceCount", evidenceIds.size(),
                "toolInvocationCount", toolInvocationIds.size()
        );
    }

    /** Calls the real Tool service and falls back to seed drafts if validation cannot resolve parts. */
    private List<AgentToolInvocationDraft> toolInvocations(AgentSessionRoot root, AgentRunProfile profile) {
        try {
            return AgentRunTraceDrafts.toolInvocationsFromResults(
                    root,
                    profile,
                    toolCheckService.checkAgentTools(root.type().name(), root.publicId(), profile.toolNames())
            );
        } catch (RuntimeException ignored) {
            return AgentRunTraceDrafts.toolInvocations(root, profile);
        }
    }
}
