package com.buildgraph.prototype.ticket.contract;

public enum BlockingFactor {
    OS_NOT_BOOTING,
    NETWORK_UNAVAILABLE,
    QUICK_ASSIST_UNAVAILABLE,
    USER_CONSENT_REQUIRED,
    ADMIN_APPROVAL_REQUIRED,
    DATA_QUALITY_LOW,
    OUT_OF_SCOPE,
    RAW_LOG_UNAVAILABLE,
    BACKUP_REQUIRED,
    RESTORE_POINT_REQUIRED,
    NO_UPLOAD_CONSENT,
    INSUFFICIENT_LOG_RANGE,
    DEVICE_OFFLINE,
    REMOTE_HELP_NOT_AVAILABLE,
    ADMIN_APPROVAL_PENDING,
    HIGH_RISK_HARDWARE_DAMAGE,
    CUSTOMER_UNAVAILABLE,
    UNSUPPORTED_SCOPE,
    OUT_OF_PC_SCOPE,
    DATA_RECOVERY_REQUIRED,
    UNSUPPORTED_SOFTWARE,
    PHYSICAL_DAMAGE_POLICY_REQUIRED
}
