package com.buildgraph.prototype.ticket.contract;

public enum SymptomType {
    REMOTE_AGENT,
    REMOTE_DRIVER_OS,
    REMOTE_APP_LAUNCHER,
    REMOTE_STORAGE_MEMORY,
    REMOTE_STARTUP_SERVICE,
    REMOTE_LOCAL_NETWORK,
    VISIT_BOOT_REMOTE_BLOCKED,
    VISIT_DISK_FAILURE,
    VISIT_WHEA_BSOD,
    VISIT_POWER_SHUTDOWN,
    VISIT_FAN_THERMAL,
    UNSUPPORTED_GAME_FPS_TUNING,
    UNSUPPORTED_OVERCLOCK_STABILITY,
    UNSUPPORTED_ISP_ROUTER,
    UNSUPPORTED_PERIPHERAL_PRINTER,
    UNSUPPORTED_DATA_RECOVERY,
    UNSUPPORTED_ILLEGAL_SOFTWARE,
    UNSUPPORTED_PHYSICAL_DAMAGE
}
