package com.buildgraph.prototype.ticket.contract;

public enum VisitReason {
    BOOT_UNAVAILABLE,
    REMOTE_CONNECTION_UNAVAILABLE,
    QUICK_ASSIST_UNAVAILABLE,
    SMART_CRITICAL,
    BAD_BLOCK,
    DISK_IO_ERROR_REPEAT,
    WHEA_HARDWARE_ERROR,
    BSOD_REPEAT,
    KERNEL_POWER_REPEAT,
    POWER_SHUTDOWN_UNDER_LOAD,
    FAN_NOT_WORKING,
    THERMAL_SHUTDOWN,
    HARDWARE_DEVICE_NOT_DETECTED,
    SUSPECTED_HARDWARE_FAILURE,
    PSU_OR_POWER_PATH_RISK,
    THERMAL_SERVICE_REQUIRED,
    STORAGE_REPLACEMENT_SUSPECTED,
    NEEDS_BENCH_REPRODUCTION,
    DEVICE_OFFLINE,
    REMOTE_HELP_NOT_AVAILABLE,
    BSOD_SIGNATURE
}
