-- Track required public FPS evidence coverage without fabricating missing FPS values.

CREATE TABLE IF NOT EXISTS game_fps_coverage_targets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  target_type VARCHAR(40) NOT NULL,
  game_title VARCHAR(160) NOT NULL,
  game_key VARCHAR(120) NOT NULL,
  resolution VARCHAR(30),
  graphics_preset VARCHAR(80),
  gpu_class VARCHAR(80),
  cpu_class VARCHAR(80),
  priority VARCHAR(20) NOT NULL DEFAULT 'P1',
  status VARCHAR(30) NOT NULL DEFAULT 'NEEDS_SOURCE',
  reason TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_game_fps_coverage_target_type CHECK (target_type IN ('GAME_RESOLUTION', 'GPU_CLASS_GAME', 'CPU_CLASS_GAME')),
  CONSTRAINT chk_game_fps_coverage_resolution CHECK (resolution IS NULL OR resolution IN ('FHD', 'QHD', '4K')),
  CONSTRAINT chk_game_fps_coverage_priority CHECK (priority IN ('P0', 'P1', 'P2')),
  CONSTRAINT chk_game_fps_coverage_status CHECK (status IN ('NEEDS_SOURCE', 'SEEDED', 'DEFERRED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_game_fps_coverage_target
  ON game_fps_coverage_targets(
    target_type,
    game_key,
    coalesce(resolution, ''),
    coalesce(graphics_preset, ''),
    coalesce(gpu_class, ''),
    coalesce(cpu_class, '')
  )
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_game_fps_coverage_target_lookup
  ON game_fps_coverage_targets(game_key, resolution, gpu_class, cpu_class)
  WHERE deleted_at IS NULL;

WITH game_targets AS (
  SELECT *
  FROM (VALUES
    ('PlayerUnknown''s Battlegrounds', 'pubg', 'ULTRA', '배틀그라운드는 핵심 데모 게임이다. FHD/QHD/4K FPS 참고값이 필요하다.'),
    ('Valorant', 'valorant', 'HIGH', '발로란트는 고주사율 e스포츠 데모 기준이다. FHD/QHD/4K FPS 참고값이 필요하다.'),
    ('Overwatch 2', 'overwatch-2', 'HIGH', '오버워치2는 일반 게이밍 데모 기준이다. FHD/QHD/4K FPS 참고값이 필요하다.'),
    ('Lost Ark', 'lost-ark', 'HIGH', '로스트아크는 CPU 영향이 큰 국내 게임 데모 기준이다. FHD/QHD/4K FPS 참고값이 필요하다.'),
    ('Cyberpunk 2077', 'cyberpunk-2077', 'RT_OVERDRIVE', '사이버펑크 2077은 고부하 그래픽 데모 기준이다. FHD/QHD/4K FPS 참고값이 필요하다.')
  ) AS target(game_title, game_key, graphics_preset, reason)
),
resolutions AS (
  SELECT *
  FROM (VALUES ('FHD', 'P0'), ('QHD', 'P0'), ('4K', 'P1')) AS resolution(resolution, priority)
)
INSERT INTO game_fps_coverage_targets (
  target_type,
  game_title,
  game_key,
  resolution,
  graphics_preset,
  priority,
  reason,
  metadata,
  created_at,
  updated_at
)
SELECT 'GAME_RESOLUTION',
       game_targets.game_title,
       game_targets.game_key,
       resolutions.resolution,
       game_targets.graphics_preset,
       resolutions.priority,
       game_targets.reason,
       jsonb_build_object(
         'targetPolicy', 'MINIMUM_GAME_RESOLUTION_COVERAGE',
         'seedRule', 'SOURCE_VERIFIED_ONLY',
         'guaranteePolicy', 'NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE'
       ),
       now(),
       now()
FROM game_targets
CROSS JOIN resolutions
ON CONFLICT DO NOTHING;

WITH gpu_targets AS (
  SELECT *
  FROM (VALUES
    ('RTX_5060', 'P1'),
    ('RTX_5060_TI', 'P0'),
    ('RTX_5070', 'P0'),
    ('RTX_5070_TI', 'P0'),
    ('RTX_5080', 'P0'),
    ('RTX_5090', 'P0')
  ) AS target(gpu_class, priority)
)
INSERT INTO game_fps_coverage_targets (
  target_type,
  game_title,
  game_key,
  resolution,
  graphics_preset,
  gpu_class,
  priority,
  reason,
  metadata,
  created_at,
  updated_at
)
SELECT 'GPU_CLASS_GAME',
       'PlayerUnknown''s Battlegrounds',
       'pubg',
       'FHD',
       'ULTRA',
       gpu_targets.gpu_class,
       gpu_targets.priority,
       '내부 RTX 50 GPU 등급별 최소 PUBG FHD Ultra FPS 참고값이 필요하다.',
       jsonb_build_object(
         'targetPolicy', 'MINIMUM_GPU_CLASS_GAME_COVERAGE',
         'seedRule', 'SOURCE_VERIFIED_ONLY',
         'guaranteePolicy', 'NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE'
       ),
       now(),
       now()
FROM gpu_targets
ON CONFLICT DO NOTHING;

CREATE OR REPLACE VIEW game_fps_coverage_status AS
SELECT target.public_id::text AS target_id,
       target.target_type,
       target.game_title,
       target.game_key,
       target.resolution,
       target.graphics_preset,
       target.gpu_class,
       target.cpu_class,
       target.priority,
       target.status AS target_status,
       coalesce(match_count.matched_rows, 0) AS matched_rows,
       CASE
         WHEN target.status = 'DEFERRED' THEN 'DEFERRED'
         WHEN coalesce(match_count.matched_rows, 0) > 0 THEN 'SEEDED'
         ELSE 'GAP'
       END AS coverage_status,
       target.reason,
       target.metadata
FROM game_fps_coverage_targets target
LEFT JOIN LATERAL (
  SELECT count(*) AS matched_rows
  FROM game_fps_benchmarks fps
  WHERE fps.deleted_at IS NULL
    AND fps.game_key = target.game_key
    AND (target.resolution IS NULL OR fps.resolution = target.resolution)
    AND (target.graphics_preset IS NULL OR fps.graphics_preset = target.graphics_preset)
    AND (target.gpu_class IS NULL OR fps.metadata->>'gpuClass' = target.gpu_class)
    AND (target.cpu_class IS NULL OR fps.metadata->>'cpuClass' = target.cpu_class)
) match_count ON true
WHERE target.deleted_at IS NULL;

CREATE OR REPLACE VIEW game_fps_coverage_gaps AS
SELECT *
FROM game_fps_coverage_status
WHERE coverage_status = 'GAP';

SELECT setval(pg_get_serial_sequence('game_fps_coverage_targets', 'id'), (SELECT max(id) FROM game_fps_coverage_targets));
