INSERT INTO manufacturer_sources (
  public_id,
  manufacturer,
  category_scope,
  source_type,
  source_url,
  enabled,
  poll_interval_minutes,
  parser_config,
  status,
  created_at,
  updated_at
)
VALUES
  (
    '00000000-0000-4000-8000-000000009521',
    'ASUS',
    'ALL',
    'NEWS',
    'https://press.asus.com/',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "ASUS official pressroom. Scan records posts and creates candidates only after product classification."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009522',
    'MSI',
    'ALL',
    'NEWS',
    'https://www.msi.com/news',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "MSI official news page."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009523',
    'GIGABYTE',
    'ALL',
    'NEWS',
    'https://www.gigabyte.com/press/news',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "GIGABYTE official newsroom."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009524',
    'ASRock',
    'ALL',
    'NEWS',
    'https://www.asrock.com/news/index.asp',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "ASRock official news page."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009525',
    'ZOTAC',
    'GPU',
    'PRODUCT_RELEASE',
    'https://www.zotac.com/news',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "ZOTAC official news/blog page for GPU and Mini PC announcements."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009526',
    'CORSAIR',
    'ALL',
    'NEWS',
    'https://www.corsair.com/newsroom/press-release/category/product-announcements',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "CORSAIR product announcements page for cases, cooling, memory, PSU and accessories."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009527',
    'Cooler Master',
    'ALL',
    'NEWS',
    'https://www.coolermaster.com/en-global/newsroom.html',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "Cooler Master newsroom for cases, cooling, PSU and related launches."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009528',
    'LIAN LI',
    'ALL',
    'NEWS',
    'https://lian-li.com/news/',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "LIAN LI official news page for cases, cooling and PSU launches."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  ),
  (
    '00000000-0000-4000-8000-000000009529',
    'Fractal Design',
    'CASE',
    'NEWS',
    'https://www.fractal-design.com/news/',
    true,
    1440,
    '{"seeded": true, "sourceRole": "OFFICIAL_MANUFACTURER_NEWS", "note": "Fractal Design official news page for case and cooling product news."}'::jsonb,
    'ACTIVE',
    now(),
    now()
  )
ON CONFLICT (source_url) WHERE deleted_at IS NULL
DO UPDATE SET
  manufacturer = EXCLUDED.manufacturer,
  category_scope = EXCLUDED.category_scope,
  source_type = EXCLUDED.source_type,
  enabled = EXCLUDED.enabled,
  poll_interval_minutes = EXCLUDED.poll_interval_minutes,
  parser_config = EXCLUDED.parser_config,
  status = 'ACTIVE',
  error_summary = NULL,
  updated_at = now();
