-- 감사 후속 2: 게임 FPS 커버리지 완전 정합 — 5게임×6 GPU 매트릭스의 남은 갭 3조합 채움.
-- V111 후 매트릭스 점검에서 발견: 오버워치2×RTX_5070_TI, 사이버펑크×RTX_5060_TI, 발로란트×RTX_5060_TI.
-- 공개 소스(CheckFPS/GamersNexus/HowManyFPS) 웹 검증(2026-07-07). 발로란트 4K(5060Ti)는 공개 실측 부재·순수 외삽이라 정책상 제외.
-- 정책: 정확 FPS 보장 아님. gpuClass 매칭 + 대표 part_id.

-- Overwatch 2 — ['RTX_5070_TI']
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Overwatch 2', 'overwatch-2', NULL, 11667, 'FHD', 'ULTRA', 414, NULL, 'CheckFPS FPS calculator', 'https://checkfps.io/en/fps-calculator/overwatch-2', DATE '2026-07-07', 'MEDIUM', '{"aliases": ["오버워치", "오버워치2", "overwatch", "overwatch 2"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5070_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5070 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "1920 x 1080", "sourceCapturedText": "FHD ULTRA, avg 414", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. CheckFPS 데스크톱 RTX 5070 Ti Ultra 추정 평균 414fps @1080p; checkfps.io/en/fps-calculator/overwatch-2/rtx-5070-ti", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Overwatch 2', 'overwatch-2', NULL, 11667, 'QHD', 'ULTRA', 349, NULL, 'CheckFPS FPS calculator', 'https://checkfps.io/en/fps-calculator/overwatch-2', DATE '2026-07-07', 'MEDIUM', '{"aliases": ["오버워치", "오버워치2", "overwatch", "overwatch 2"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5070_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5070 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "2560 x 1440", "sourceCapturedText": "QHD ULTRA, avg 349", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. CheckFPS 데스크톱 RTX 5070 Ti Ultra 추정 평균 349fps @1440p; 1080p>1440p 물리적 정합; checkfps.io/en/fps-calculator/overwatch-2/rtx-5070-ti", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Overwatch 2', 'overwatch-2', NULL, 11667, '4K', 'ULTRA', 223, NULL, 'CheckFPS FPS calculator', 'https://checkfps.io/en/fps-calculator/overwatch-2', DATE '2026-07-07', 'MEDIUM', '{"aliases": ["오버워치", "오버워치2", "overwatch", "overwatch 2"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5070_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5070 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "3840 x 2160", "sourceCapturedText": "4K ULTRA, avg 223", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. CheckFPS 데스크톱 RTX 5070 Ti Ultra 추정 평균 223fps @4K; RTX 5070(171fps)보다 상위 정합; checkfps.io/en/fps-calculator/overwatch-2/rtx-5070-ti", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());

-- Cyberpunk 2077 — ['RTX_5060_TI']
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Cyberpunk 2077', 'cyberpunk-2077', NULL, 11683, 'FHD', 'ULTRA', 93, NULL, 'GamersNexus RTX 5060 Ti Review (corroborated by HowManyFPS)', 'https://www.gamersnexus.net/gpus', DATE '2026-07-07', 'HIGH', '{"aliases": ["사이버펑크", "사펑", "cyberpunk", "cyberpunk 2077"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5060_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5060 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "1920 x 1080", "sourceCapturedText": "FHD ULTRA, avg 93", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. Cyberpunk 2077 Phantom Liberty, Ultra preset, no ray tracing, 1080p = 93 FPS AVG. gamersnexus.net/gpus/more-marketing-bs-nvidia-geforce-rtx-5060-ti-review-benchmarks; howmanyfps.com/graphics-cards/gef", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Cyberpunk 2077', 'cyberpunk-2077', NULL, 11683, 'QHD', 'ULTRA', 68, NULL, 'GamersNexus RTX 5060 Ti Review (corroborated by HowManyFPS)', 'https://www.gamersnexus.net/gpus', DATE '2026-07-07', 'HIGH', '{"aliases": ["사이버펑크", "사펑", "cyberpunk", "cyberpunk 2077"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5060_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5060 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "2560 x 1440", "sourceCapturedText": "QHD ULTRA, avg 68", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. Cyberpunk 2077 Phantom Liberty, Ultra preset, no ray tracing, 1440p = 68 FPS AVG. Consistent with TechSpot ~66 fps for near-tier RTX 5060. gamersnexus.net/gpus/more-marketing-bs-nvidia-geforce-rtx-506", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Cyberpunk 2077', 'cyberpunk-2077', NULL, 11683, '4K', 'ULTRA', 31, NULL, 'GamersNexus RTX 5060 Ti Review', 'https://www.gamersnexus.net/gpus', DATE '2026-07-07', 'MEDIUM', '{"aliases": ["사이버펑크", "사펑", "cyberpunk", "cyberpunk 2077"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5060_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5060 Ti", "sourcePresetText": "ULTRA", "sourceResolutionText": "3840 x 2160", "sourceCapturedText": "4K ULTRA, avg 31", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. Cyberpunk 2077 Phantom Liberty, Ultra preset, no ray tracing, 4K/2160p = 31 FPS AVG (native, no upscaling). gamersnexus.net/gpus/more-marketing-bs-nvidia-geforce-rtx-5060-ti-review-benchmarks", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());

-- Valorant — ['RTX_5060_TI']
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Valorant', 'valorant', NULL, 11683, 'FHD', 'HIGH', 300, NULL, 'PC Build Helper / HowManyFPS (aggregator estimate)', 'https://howmanyfps.com/graphics-cards', DATE '2026-07-07', 'LOW', '{"aliases": ["발로", "발로란트", "valorant"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5060_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5060 Ti", "sourcePresetText": "HIGH", "sourceResolutionText": "1920 x 1080", "sourceCapturedText": "FHD HIGH, avg 300", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. Valorant은 경량 e스포츠 타이틀. RTX 5060(비-Ti)이 1080p high에서 ~280fps 보고, 5060 Ti는 한 단계 위(HowManyFPS: 5060보다 빠름)라 ~300fps로 추정. 강한 CPU 전제. 하드 벤치표 접근 불가로 LOW. src: pcbuildhelper.com/article/best-pc-builds-for-val", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
INSERT INTO game_fps_benchmarks (public_id, game_title, game_key, cpu_part_id, gpu_part_id, resolution, graphics_preset, avg_fps, one_percent_low_fps, source_name, source_url, source_checked_at, confidence, metadata, created_at)
VALUES (gen_random_uuid(), 'Valorant', 'valorant', NULL, 11683, 'QHD', 'HIGH', 260, NULL, 'PC Build Helper / HowManyFPS (aggregator estimate)', 'https://howmanyfps.com/graphics-cards', DATE '2026-07-07', 'LOW', '{"aliases": ["발로", "발로란트", "valorant"], "cpuClass": "RYZEN_7_9800X3D", "gpuClass": "RTX_5060_TI", "guaranteePolicy": "NO_EXACT_FPS_OR_RENDER_TIME_GUARANTEE", "evidenceExactness": "FPS_CALCULATOR_EXACT_PARTS", "hardwareScope": "FPS_CALCULATOR_EXACT_PARTS", "sourceMetricType": "FPS_CALCULATOR_EXACT_PARTS", "sourceCpuName": "Ryzen 7 9800X3D", "sourceGpuName": "GeForce RTX 5060 Ti", "sourcePresetText": "HIGH", "sourceResolutionText": "2560 x 1440", "sourceCapturedText": "QHD HIGH, avg 260", "sourceAccessMethod": "MANUAL_PAGE_READ", "osVersion": "UNKNOWN_PUBLIC_SOURCE", "driverVersion": "UNKNOWN_PUBLIC_SOURCE", "gameVersion": "UNKNOWN_PUBLIC_SOURCE", "testScene": "UNKNOWN_PUBLIC_SOURCE", "upscaling": "UNKNOWN_PUBLIC_SOURCE", "frameGeneration": "UNKNOWN_PUBLIC_SOURCE", "rayTracing": "NOT_SPECIFIED", "notes": "Public FPS reference for recommendation evidence. Do not present as guaranteed FPS. 5060이 1440p 경쟁/high 설정에서 300~350+fps 보고(대개 low/최적화 프리셋). 5060 Ti high 프리셋 대표 평균은 ~260fps로 보수 추정, FHD>QHD 단조 유지. 직접 high-프리셋 QHD 벤치표 미확보로 LOW. src: pcbuildhelper.com/article/best-pc-builds-for-valorant", "qualityGaps": ["one_percent_low_fps_not_provided"], "metadataVersion": 1}'::jsonb, now());
-- SKIP valorant RTX_5060_TI 4K: extrapolation (no direct 4K Valorant benchmark found) (외삽/미확인 제외)

