CREATE TABLE llm_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  agent_session_id BIGINT NOT NULL REFERENCES agent_sessions(id),
  ai_profile VARCHAR(60) NOT NULL,
  provider VARCHAR(40) NOT NULL DEFAULT 'openai',
  model VARCHAR(120) NOT NULL,
  reasoning_effort VARCHAR(30),
  use_case VARCHAR(60) NOT NULL,
  status VARCHAR(30) NOT NULL,
  schema_name VARCHAR(120),
  rag_top_k INTEGER NOT NULL,
  prompt_version VARCHAR(120) NOT NULL,
  latency_ms BIGINT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  total_tokens INTEGER,
  schema_valid BOOLEAN NOT NULL DEFAULT false,
  error_code VARCHAR(80),
  error_message TEXT,
  request_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_llm_generations_profile CHECK (ai_profile IN ('AS_CHAT_FAST', 'AS_CHAT_BALANCED', 'AS_CHAT_HIGH_QUALITY')),
  CONSTRAINT chk_llm_generations_status CHECK (status IN ('SUCCESS', 'FAILED')),
  CONSTRAINT chk_llm_generations_latency CHECK (latency_ms IS NULL OR latency_ms >= 0),
  CONSTRAINT chk_llm_generations_tokens CHECK (
    (input_tokens IS NULL OR input_tokens >= 0)
    AND (output_tokens IS NULL OR output_tokens >= 0)
    AND (total_tokens IS NULL OR total_tokens >= 0)
  ),
  CONSTRAINT chk_llm_generations_rag_top_k CHECK (rag_top_k > 0)
);

CREATE INDEX idx_llm_generations_agent_session_id ON llm_generations(agent_session_id);
CREATE INDEX idx_llm_generations_profile_created_at ON llm_generations(ai_profile, created_at);
CREATE INDEX idx_llm_generations_status_created_at ON llm_generations(status, created_at);
CREATE INDEX idx_llm_generations_model_created_at ON llm_generations(model, created_at);
