CREATE TABLE parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  category VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  manufacturer VARCHAR(100),
  price INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  attributes JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_parts_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_parts_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED')),
  CONSTRAINT chk_parts_price CHECK (price >= 0)
);

CREATE INDEX idx_parts_category ON parts(category);
CREATE INDEX idx_parts_status ON parts(status);
CREATE INDEX idx_parts_name ON parts(name);
CREATE INDEX idx_parts_deleted_at ON parts(deleted_at);

CREATE TABLE price_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id BIGINT NOT NULL REFERENCES parts(id),
  price INTEGER NOT NULL,
  source VARCHAR(100) NOT NULL,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw_payload JSONB,
  CONSTRAINT chk_price_snapshots_price CHECK (price >= 0)
);

CREATE INDEX idx_price_snapshots_part_id ON price_snapshots(part_id);
CREATE INDEX idx_price_snapshots_part_collected ON price_snapshots(part_id, collected_at);

CREATE TABLE price_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  part_id BIGINT NOT NULL REFERENCES parts(id),
  target_price INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_price_alerts_status CHECK (status IN ('ACTIVE', 'TRIGGERED', 'DISABLED')),
  CONSTRAINT chk_price_alerts_target_price CHECK (target_price >= 0)
);

CREATE INDEX idx_price_alerts_user_status ON price_alerts(user_id, status);
CREATE INDEX idx_price_alerts_part_target ON price_alerts(part_id, target_price);
CREATE INDEX idx_price_alerts_deleted_at ON price_alerts(deleted_at);
CREATE UNIQUE INDEX ux_price_alerts_active_user_part_target
  ON price_alerts(user_id, part_id, target_price)
  WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE TABLE price_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  requested_by BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(30) NOT NULL,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  error_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_price_jobs_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX idx_price_jobs_status ON price_jobs(status);
CREATE INDEX idx_price_jobs_created_at ON price_jobs(created_at);
CREATE UNIQUE INDEX ux_price_jobs_single_active
  ON price_jobs((1))
  WHERE status IN ('QUEUED', 'RUNNING') AND deleted_at IS NULL;

CREATE TABLE compatibility_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key VARCHAR(120) NOT NULL UNIQUE,
  category VARCHAR(50) NOT NULL,
  "condition" JSONB NOT NULL,
  result_status VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_compatibility_rules_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_compatibility_rules_result_status CHECK (result_status IN ('PASS', 'WARN', 'FAIL'))
);

CREATE INDEX idx_compatibility_rules_category ON compatibility_rules(category);
CREATE INDEX idx_compatibility_rules_deleted_at ON compatibility_rules(deleted_at);

CREATE TABLE benchmark_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id BIGINT REFERENCES parts(id),
  benchmark_key VARCHAR(120) NOT NULL UNIQUE,
  summary TEXT NOT NULL,
  score NUMERIC(10, 2),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_benchmark_summaries_part_id ON benchmark_summaries(part_id);
CREATE INDEX idx_benchmark_summaries_deleted_at ON benchmark_summaries(deleted_at);
