CREATE TABLE requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  raw_message TEXT NOT NULL,
  budget INTEGER,
  usage_tags TEXT[],
  parsed_context JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_requirements_budget CHECK (budget IS NULL OR budget >= 0)
);

CREATE INDEX idx_requirements_user_id ON requirements(user_id);
CREATE INDEX idx_requirements_created_at ON requirements(created_at);

CREATE TABLE builds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  requirement_id BIGINT NOT NULL REFERENCES requirements(id),
  name VARCHAR(120) NOT NULL,
  total_price INTEGER NOT NULL,
  confidence VARCHAR(30) NOT NULL,
  warnings JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_builds_confidence CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT chk_builds_total_price CHECK (total_price >= 0)
);

CREATE INDEX idx_builds_requirement_id ON builds(requirement_id);
CREATE INDEX idx_builds_created_at ON builds(created_at);

CREATE TABLE build_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  build_id BIGINT NOT NULL REFERENCES builds(id),
  part_id BIGINT NOT NULL REFERENCES parts(id),
  category VARCHAR(50) NOT NULL,
  price INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_build_items_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_build_items_price CHECK (price >= 0),
  CONSTRAINT ux_build_items_build_category UNIQUE (build_id, category)
);

CREATE INDEX idx_build_items_build_id ON build_items(build_id);
CREATE INDEX idx_build_items_part_id ON build_items(part_id);
