CREATE TABLE manufacturer_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  manufacturer VARCHAR(100) NOT NULL,
  category_scope VARCHAR(50) NOT NULL,
  source_type VARCHAR(50) NOT NULL,
  source_url TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  poll_interval_minutes INTEGER NOT NULL DEFAULT 1440,
  last_checked_at TIMESTAMPTZ,
  last_etag VARCHAR(255),
  last_modified VARCHAR(255),
  last_content_hash VARCHAR(128),
  parser_config JSONB,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  error_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_manufacturer_sources_category_scope CHECK (category_scope IN ('ALL', 'CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_manufacturer_sources_source_type CHECK (source_type IN ('NEWS', 'PRODUCT_RELEASE', 'SUPPORT_NEWS', 'RSS', 'SITEMAP')),
  CONSTRAINT chk_manufacturer_sources_status CHECK (status IN ('ACTIVE', 'PAUSED', 'ERROR')),
  CONSTRAINT chk_manufacturer_sources_poll_interval CHECK (poll_interval_minutes BETWEEN 30 AND 10080)
);

CREATE UNIQUE INDEX ux_manufacturer_sources_url_active
  ON manufacturer_sources(source_url)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_manufacturer_sources_enabled ON manufacturer_sources(enabled);
CREATE INDEX idx_manufacturer_sources_manufacturer ON manufacturer_sources(manufacturer);
CREATE INDEX idx_manufacturer_sources_category_scope ON manufacturer_sources(category_scope);
CREATE INDEX idx_manufacturer_sources_deleted_at ON manufacturer_sources(deleted_at);

CREATE TABLE manufacturer_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  manufacturer_source_id BIGINT NOT NULL REFERENCES manufacturer_sources(id),
  created_catalog_candidate_id BIGINT REFERENCES part_catalog_candidates(id),
  external_url TEXT NOT NULL,
  title VARCHAR(500) NOT NULL,
  published_at TIMESTAMPTZ,
  content_hash VARCHAR(128) NOT NULL,
  excerpt TEXT,
  raw_payload JSONB,
  classification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  detected_category VARCHAR(50),
  detected_product_name VARCHAR(255),
  confidence NUMERIC(5, 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_manufacturer_posts_classification_status CHECK (classification_status IN ('PENDING', 'PRODUCT_CANDIDATE', 'IGNORED', 'FAILED')),
  CONSTRAINT chk_manufacturer_posts_detected_category CHECK (detected_category IS NULL OR detected_category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_manufacturer_posts_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE UNIQUE INDEX ux_manufacturer_posts_source_url_active
  ON manufacturer_posts(manufacturer_source_id, external_url)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_manufacturer_posts_source_id ON manufacturer_posts(manufacturer_source_id);
CREATE INDEX idx_manufacturer_posts_classification_status ON manufacturer_posts(classification_status);
CREATE INDEX idx_manufacturer_posts_detected_category ON manufacturer_posts(detected_category);
CREATE INDEX idx_manufacturer_posts_candidate_id ON manufacturer_posts(created_catalog_candidate_id);
CREATE INDEX idx_manufacturer_posts_created_at ON manufacturer_posts(created_at);
CREATE INDEX idx_manufacturer_posts_deleted_at ON manufacturer_posts(deleted_at);
