CREATE TABLE agent_activation_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_activation_tokens_user_id ON agent_activation_tokens(user_id);
CREATE INDEX idx_agent_activation_tokens_expires_at ON agent_activation_tokens(expires_at);

CREATE TABLE agent_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  activation_token_id BIGINT REFERENCES agent_activation_tokens(id),
  device_fingerprint_hash VARCHAR(255) NOT NULL,
  hostname_hash VARCHAR(255),
  agent_token_hash VARCHAR(255) NOT NULL UNIQUE,
  registration_idempotency_key VARCHAR(160) NOT NULL,
  status VARCHAR(30) NOT NULL,
  os_version VARCHAR(120) NOT NULL,
  agent_version VARCHAR(50) NOT NULL,
  policy_version VARCHAR(80),
  last_seen_at TIMESTAMPTZ,
  blocked_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT uq_agent_devices_activation_idempotency UNIQUE (activation_token_id, registration_idempotency_key),
  CONSTRAINT chk_agent_devices_status CHECK (
    status IN ('PENDING_REGISTERED', 'ACTIVE', 'UPDATE_REQUIRED', 'BLOCKED', 'REVOKED', 'UNINSTALLED')
  )
);

CREATE UNIQUE INDEX uq_agent_devices_user_active
  ON agent_devices(user_id)
  WHERE status IN ('PENDING_REGISTERED', 'ACTIVE', 'UPDATE_REQUIRED', 'BLOCKED');
CREATE INDEX idx_agent_devices_user_id ON agent_devices(user_id);
CREATE INDEX idx_agent_devices_status ON agent_devices(status);
CREATE INDEX idx_agent_devices_last_seen_at ON agent_devices(last_seen_at);

CREATE TABLE agent_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  device_id BIGINT REFERENCES agent_devices(id),
  consent_type VARCHAR(50) NOT NULL,
  policy_version VARCHAR(80) NOT NULL,
  source VARCHAR(50) NOT NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  accepted BOOLEAN NOT NULL,
  accepted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_agent_consents_device_idempotency UNIQUE (device_id, idempotency_key),
  CONSTRAINT chk_agent_consents_type CHECK (
    consent_type IN ('LOCAL_COLLECTION', 'SERVER_UPLOAD', 'QUALITY_IMPROVEMENT')
  )
);

CREATE INDEX idx_agent_consents_user_id ON agent_consents(user_id);
CREATE INDEX idx_agent_consents_device_id ON agent_consents(device_id);
CREATE INDEX idx_agent_consents_user_type_created_at ON agent_consents(user_id, consent_type, created_at);

CREATE TABLE agent_heartbeats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  device_id BIGINT NOT NULL REFERENCES agent_devices(id),
  agent_version VARCHAR(50) NOT NULL,
  service_status VARCHAR(50) NOT NULL,
  tray_status VARCHAR(50),
  policy_version VARCHAR(80),
  idempotency_key VARCHAR(160) NOT NULL,
  received_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_agent_heartbeats_device_idempotency UNIQUE (device_id, idempotency_key)
);

CREATE INDEX idx_agent_heartbeats_device_received_at ON agent_heartbeats(device_id, received_at);
CREATE INDEX idx_agent_heartbeats_received_at ON agent_heartbeats(received_at);

CREATE TABLE agent_update_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  channel VARCHAR(30) NOT NULL,
  policy_version VARCHAR(80) NOT NULL,
  minimum_supported_version VARCHAR(50) NOT NULL,
  latest_version VARCHAR(50) NOT NULL,
  installer_url TEXT,
  sha256 VARCHAR(128),
  manifest_signature TEXT,
  kill_switch BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_agent_update_policies_channel_version UNIQUE (channel, policy_version),
  CONSTRAINT chk_agent_update_policies_channel CHECK (channel IN ('STABLE'))
);

CREATE INDEX idx_agent_update_policies_created_at ON agent_update_policies(created_at);

CREATE TABLE agent_update_rollouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  policy_id BIGINT NOT NULL REFERENCES agent_update_policies(id),
  version VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  CONSTRAINT chk_agent_update_rollouts_status CHECK (status IN ('ACTIVE', 'PAUSED', 'ROLLED_BACK'))
);

CREATE INDEX idx_agent_update_rollouts_policy_id ON agent_update_rollouts(policy_id);
CREATE INDEX idx_agent_update_rollouts_version_status ON agent_update_rollouts(version, status);

CREATE TABLE agent_upload_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  device_id BIGINT NOT NULL REFERENCES agent_devices(id),
  idempotency_key VARCHAR(160) NOT NULL,
  status VARCHAR(30) NOT NULL,
  range_started_at TIMESTAMPTZ NOT NULL,
  range_ended_at TIMESTAMPTZ NOT NULL,
  error_code VARCHAR(80),
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT uq_agent_upload_jobs_device_idempotency UNIQUE (device_id, idempotency_key),
  CONSTRAINT chk_agent_upload_jobs_status CHECK (
    status IN ('QUEUED', 'UPLOADING', 'UPLOADED', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'CANCELLED', 'EXPIRED')
  )
);

CREATE INDEX idx_agent_upload_jobs_status ON agent_upload_jobs(status);
CREATE INDEX idx_agent_upload_jobs_created_at ON agent_upload_jobs(created_at);

CREATE TABLE agent_log_bundles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  upload_job_id BIGINT NOT NULL REFERENCES agent_upload_jobs(id),
  log_upload_id BIGINT REFERENCES agent_log_uploads(id),
  schema_version INTEGER NOT NULL,
  storage_path TEXT NOT NULL,
  sha256 VARCHAR(128) NOT NULL UNIQUE,
  size_bytes BIGINT NOT NULL,
  delete_after TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_agent_log_bundles_schema_version CHECK (schema_version > 0),
  CONSTRAINT chk_agent_log_bundles_size_bytes CHECK (size_bytes >= 0)
);

CREATE INDEX idx_agent_log_bundles_upload_job_id ON agent_log_bundles(upload_job_id);
CREATE INDEX idx_agent_log_bundles_log_upload_id ON agent_log_bundles(log_upload_id);
CREATE INDEX idx_agent_log_bundles_delete_after ON agent_log_bundles(delete_after);

ALTER TABLE agent_log_uploads
  ADD COLUMN device_id BIGINT REFERENCES agent_devices(id),
  ADD COLUMN upload_job_id BIGINT REFERENCES agent_upload_jobs(id);

CREATE INDEX idx_agent_log_uploads_device_id ON agent_log_uploads(device_id);
CREATE INDEX idx_agent_log_uploads_upload_job_id ON agent_log_uploads(upload_job_id);

ALTER TABLE as_tickets
  ADD COLUMN analysis_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN review_status VARCHAR(30) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN support_decision VARCHAR(50),
  ADD COLUMN risk_level VARCHAR(30),
  ADD COLUMN auto_response_allowed BOOLEAN NOT NULL DEFAULT false,
  ADD CONSTRAINT chk_as_tickets_analysis_status CHECK (
    analysis_status IN ('NOT_STARTED', 'QUEUED', 'ANALYZING', 'RULE_READY', 'LLM_READY', 'FAILED')
  ),
  ADD CONSTRAINT chk_as_tickets_review_status CHECK (
    review_status IN ('NOT_REQUIRED', 'REQUIRED', 'IN_REVIEW', 'APPROVED', 'REJECTED')
  ),
  ADD CONSTRAINT chk_as_tickets_support_decision CHECK (
    support_decision IS NULL
    OR support_decision IN ('SELF_SOLVABLE', 'REMOTE_POSSIBLE', 'VISIT_REQUIRED', 'NEEDS_MORE_INFO')
  ),
  ADD CONSTRAINT chk_as_tickets_risk_level CHECK (
    risk_level IS NULL OR risk_level IN ('LOW', 'MEDIUM', 'HIGH')
  );

CREATE INDEX idx_as_tickets_analysis_status ON as_tickets(analysis_status);
CREATE INDEX idx_as_tickets_review_status ON as_tickets(review_status);
CREATE INDEX idx_as_tickets_support_decision ON as_tickets(support_decision);
CREATE INDEX idx_as_tickets_risk_level ON as_tickets(risk_level);

CREATE TABLE agent_delete_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  device_id BIGINT REFERENCES agent_devices(id),
  scope VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  reason VARCHAR(80) NOT NULL,
  requested_at TIMESTAMPTZ NOT NULL,
  processed_at TIMESTAMPTZ,
  error_message TEXT,
  CONSTRAINT uq_agent_delete_requests_device_idempotency UNIQUE (device_id, idempotency_key),
  CONSTRAINT chk_agent_delete_requests_scope CHECK (scope IN ('LOCAL_LOGS', 'SERVER_LOGS', 'ALL')),
  CONSTRAINT chk_agent_delete_requests_status CHECK (status IN ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_agent_delete_requests_user_id ON agent_delete_requests(user_id);
CREATE INDEX idx_agent_delete_requests_device_id ON agent_delete_requests(device_id);
CREATE INDEX idx_agent_delete_requests_status ON agent_delete_requests(status);

CREATE TABLE remote_support_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  as_ticket_id BIGINT NOT NULL REFERENCES as_tickets(id),
  device_id BIGINT REFERENCES agent_devices(id),
  provider VARCHAR(80) NOT NULL,
  session_url TEXT,
  status VARCHAR(30) NOT NULL,
  requested_by_admin_id BIGINT REFERENCES users(id),
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_remote_support_sessions_provider CHECK (
    provider IN ('EXTERNAL_LINK', 'ANYDESK', 'TEAMVIEWER', 'ZOOM', 'GOOGLE_MEET')
  ),
  CONSTRAINT chk_remote_support_sessions_status CHECK (
    status IN ('REQUESTED', 'LINK_SENT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')
  )
);

CREATE INDEX idx_remote_support_sessions_as_ticket_id ON remote_support_sessions(as_ticket_id);
CREATE INDEX idx_remote_support_sessions_device_id ON remote_support_sessions(device_id);
CREATE INDEX idx_remote_support_sessions_status ON remote_support_sessions(status);
CREATE INDEX idx_remote_support_sessions_created_at ON remote_support_sessions(created_at);

CREATE TABLE visit_support_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  as_ticket_id BIGINT NOT NULL REFERENCES as_tickets(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  preferred_date DATE NOT NULL,
  time_slot VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  address_snapshot TEXT,
  technician_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_visit_support_reservations_time_slot CHECK (time_slot IN ('MORNING', 'AFTERNOON', 'EVENING')),
  CONSTRAINT chk_visit_support_reservations_status CHECK (
    status IN ('REQUESTED', 'SCHEDULED', 'RESCHEDULE_REQUESTED', 'VISIT_IN_PROGRESS', 'COMPLETED', 'CANCELLED')
  )
);

CREATE INDEX idx_visit_support_reservations_as_ticket_id ON visit_support_reservations(as_ticket_id);
CREATE INDEX idx_visit_support_reservations_user_id ON visit_support_reservations(user_id);
CREATE INDEX idx_visit_support_reservations_status ON visit_support_reservations(status);
CREATE INDEX idx_visit_support_reservations_preferred_slot ON visit_support_reservations(preferred_date, time_slot);
