CREATE TABLE agent_log_uploads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  range_minutes INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_size BIGINT,
  storage_path TEXT,
  summary TEXT,
  consent_accepted_at TIMESTAMPTZ NOT NULL,
  delete_after TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_agent_log_uploads_range_minutes CHECK (range_minutes > 0),
  CONSTRAINT chk_agent_log_uploads_status CHECK (status IN ('UPLOADED', 'PROCESSING', 'FAILED')),
  CONSTRAINT chk_agent_log_uploads_file_size CHECK (file_size IS NULL OR file_size >= 0)
);

CREATE INDEX idx_agent_log_uploads_user_id ON agent_log_uploads(user_id);
CREATE INDEX idx_agent_log_uploads_status ON agent_log_uploads(status);
CREATE INDEX idx_agent_log_uploads_delete_after ON agent_log_uploads(delete_after);
CREATE INDEX idx_agent_log_uploads_created_at ON agent_log_uploads(created_at);

CREATE TABLE as_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  log_upload_id BIGINT REFERENCES agent_log_uploads(id),
  assigned_admin_id BIGINT REFERENCES users(id),
  symptom TEXT NOT NULL,
  status VARCHAR(30) NOT NULL,
  cause_candidates JSONB,
  upgrade_candidates JSONB,
  admin_note TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_as_tickets_status CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX idx_as_tickets_user_id ON as_tickets(user_id);
CREATE INDEX idx_as_tickets_log_upload_id ON as_tickets(log_upload_id);
CREATE INDEX idx_as_tickets_status ON as_tickets(status);
CREATE INDEX idx_as_tickets_assigned_admin_id ON as_tickets(assigned_admin_id);
CREATE INDEX idx_as_tickets_created_at ON as_tickets(created_at);
CREATE INDEX idx_as_tickets_deleted_at ON as_tickets(deleted_at);
