CREATE TABLE part_alias_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  category VARCHAR(50) NOT NULL,
  target_field VARCHAR(80) NOT NULL,
  alias_text VARCHAR(255) NOT NULL,
  canonical_value VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  source VARCHAR(80) NOT NULL DEFAULT 'ADMIN_REVIEW',
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_part_alias_rules_status CHECK (status IN ('ACTIVE', 'IGNORED', 'DELETED'))
);

CREATE UNIQUE INDEX uq_part_alias_rules_active_alias
  ON part_alias_rules (lower(category), lower(target_field), lower(alias_text))
  WHERE deleted_at IS NULL AND status = 'ACTIVE';

CREATE INDEX idx_part_alias_rules_category_field
  ON part_alias_rules (category, target_field, status);

CREATE TABLE part_alias_review_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source_type VARCHAR(50) NOT NULL,
  category VARCHAR(50),
  target_field VARCHAR(80),
  alias_text VARCHAR(255),
  raw_value VARCHAR(255),
  canonical_suggestion VARCHAR(255),
  part_id BIGINT REFERENCES parts(id),
  part_catalog_candidate_id BIGINT REFERENCES part_catalog_candidates(id),
  manufacturer_post_id BIGINT REFERENCES manufacturer_posts(id),
  message TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  resolution_note TEXT,
  resolved_alias_rule_id BIGINT REFERENCES part_alias_rules(id),
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_part_alias_review_items_source CHECK (source_type IN ('PART_ATTRIBUTE', 'USER_QUERY', 'NAVER_CANDIDATE', 'MANUFACTURER_POST', 'AI_BUILD_CHAT')),
  CONSTRAINT chk_part_alias_review_items_status CHECK (status IN ('OPEN', 'RESOLVED', 'IGNORED'))
);

CREATE UNIQUE INDEX uq_part_alias_review_items_open_dedupe
  ON part_alias_review_items (
    source_type,
    lower(coalesce(category, '')),
    lower(coalesce(target_field, '')),
    lower(coalesce(alias_text, '')),
    lower(coalesce(raw_value, ''))
  )
  WHERE deleted_at IS NULL AND status = 'OPEN';

CREATE INDEX idx_part_alias_review_items_status
  ON part_alias_review_items (status, category, created_at DESC);
