CREATE TABLE IF NOT EXISTS agent_log_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  log_upload_id BIGINT NOT NULL REFERENCES agent_log_uploads(id),
  as_ticket_id BIGINT REFERENCES as_tickets(id),
  summary_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  feature_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  event_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  risk_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
  privacy_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_agent_log_summaries_log_upload UNIQUE (log_upload_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_log_summaries_as_ticket_id ON agent_log_summaries(as_ticket_id);
CREATE INDEX IF NOT EXISTS idx_agent_log_summaries_created_at ON agent_log_summaries(created_at);

CREATE TABLE IF NOT EXISTS as_ticket_labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  as_ticket_id BIGINT NOT NULL REFERENCES as_tickets(id),
  log_summary_id BIGINT REFERENCES agent_log_summaries(id),
  failure_category VARCHAR(60) NOT NULL,
  severity VARCHAR(30) NOT NULL,
  related_part_id BIGINT REFERENCES parts(id),
  related_build_id BIGINT REFERENCES builds(id),
  recommendation_id VARCHAR(160),
  use_for_recommendation_training BOOLEAN NOT NULL DEFAULT false,
  note TEXT,
  labeled_by_admin_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT uq_as_ticket_labels_ticket UNIQUE (as_ticket_id),
  CONSTRAINT chk_as_ticket_labels_failure_category CHECK (
    failure_category IN (
      'RECOMMENDATION_BUILD',
      'PART_SELECTION',
      'COMPATIBILITY',
      'PERFORMANCE',
      'USER_ENVIRONMENT',
      'AGENT_LOG_ONLY',
      'OTHER'
    )
  ),
  CONSTRAINT chk_as_ticket_labels_severity CHECK (
    severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
  )
);

CREATE INDEX IF NOT EXISTS idx_as_ticket_labels_training ON as_ticket_labels(use_for_recommendation_training, created_at);
CREATE INDEX IF NOT EXISTS idx_as_ticket_labels_related_part ON as_ticket_labels(related_part_id);
CREATE INDEX IF NOT EXISTS idx_as_ticket_labels_related_build ON as_ticket_labels(related_build_id);
