CREATE TABLE agent_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  requirement_id BIGINT REFERENCES requirements(id),
  build_id BIGINT REFERENCES builds(id),
  as_ticket_id BIGINT REFERENCES as_tickets(id),
  status VARCHAR(30) NOT NULL,
  summary TEXT,
  state_timeline JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_agent_sessions_status CHECK (
    status IN (
      'QUEUED',
      'RUNNING',
      'RAG_SEARCHED',
      'TOOLS_CALLED',
      'SUMMARY_READY',
      'FALLBACK_READY',
      'SUCCEEDED',
      'FAILED',
      'CANCELLED'
    )
  )
);

CREATE INDEX idx_agent_sessions_user_id ON agent_sessions(user_id);
CREATE INDEX idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX idx_agent_sessions_requirement_id ON agent_sessions(requirement_id);
CREATE INDEX idx_agent_sessions_build_id ON agent_sessions(build_id);
CREATE INDEX idx_agent_sessions_as_ticket_id ON agent_sessions(as_ticket_id);

CREATE TABLE tool_invocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  agent_session_id BIGINT NOT NULL REFERENCES agent_sessions(id),
  tool_name VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  confidence VARCHAR(30) NOT NULL,
  summary TEXT NOT NULL,
  request_payload JSONB,
  result_payload JSONB,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_tool_invocations_tool_name CHECK (tool_name IN ('compatibility', 'power', 'size', 'performance', 'price')),
  CONSTRAINT chk_tool_invocations_status CHECK (status IN ('PASS', 'WARN', 'FAIL')),
  CONSTRAINT chk_tool_invocations_confidence CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT chk_tool_invocations_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX idx_tool_invocations_agent_session_id ON tool_invocations(agent_session_id);
CREATE INDEX idx_tool_invocations_tool_status ON tool_invocations(tool_name, status);
CREATE INDEX idx_tool_invocations_created_at ON tool_invocations(created_at);

CREATE TABLE rag_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  agent_session_id BIGINT REFERENCES agent_sessions(id),
  source_id VARCHAR(120) NOT NULL,
  chunk_text TEXT NOT NULL,
  summary TEXT NOT NULL,
  score NUMERIC(8, 5),
  embedding vector(1536),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_rag_evidence_score CHECK (score IS NULL OR (score >= 0 AND score <= 1))
);

CREATE INDEX idx_rag_evidence_agent_session_id ON rag_evidence(agent_session_id);
CREATE INDEX idx_rag_evidence_source_id ON rag_evidence(source_id);
CREATE INDEX idx_rag_evidence_score ON rag_evidence(score);
