CREATE TABLE IF NOT EXISTS as_rag_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source_id VARCHAR(160) NOT NULL UNIQUE,
  symptom_type VARCHAR(80),
  source_type VARCHAR(60) NOT NULL,
  recommended_service VARCHAR(40) NOT NULL,
  support_decision VARCHAR(50) NOT NULL,
  reason_code VARCHAR(80) NOT NULL,
  title TEXT NOT NULL,
  chunk_text TEXT NOT NULL,
  summary TEXT NOT NULL,
  score NUMERIC(8, 5) NOT NULL DEFAULT 0.70,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_as_rag_evidence_service CHECK (
    recommended_service IN ('DIAGNOSIS_ONLY', 'REMOTE_SUPPORT', 'VISIT_SUPPORT')
  ),
  CONSTRAINT chk_as_rag_evidence_decision CHECK (
    support_decision IN (
      'SELF_SOLVABLE',
      'REMOTE_POSSIBLE',
      'VISIT_REQUIRED',
      'REPAIR_OR_REPLACE',
      'NEEDS_MORE_INFO',
      'MONITOR_ONLY',
      'UNSUPPORTED'
    )
  ),
  CONSTRAINT chk_as_rag_evidence_score CHECK (score >= 0 AND score <= 1)
);

CREATE INDEX IF NOT EXISTS idx_as_rag_evidence_service
  ON as_rag_evidence(recommended_service, support_decision);

CREATE INDEX IF NOT EXISTS idx_as_rag_evidence_symptom_type
  ON as_rag_evidence(symptom_type);

CREATE INDEX IF NOT EXISTS idx_as_rag_evidence_active_score
  ON as_rag_evidence(active, score DESC);

ALTER TABLE agent_log_uploads
  ADD COLUMN IF NOT EXISTS as_rag_analysis JSONB;

INSERT INTO as_rag_evidence (
  source_id,
  symptom_type,
  source_type,
  recommended_service,
  support_decision,
  reason_code,
  title,
  chunk_text,
  summary,
  score,
  metadata
) VALUES
(
  'as-rag-remote-driver-os',
  'REMOTE_DRIVER_OS',
  'TROUBLESHOOTING',
  'REMOTE_SUPPORT',
  'REMOTE_POSSIBLE',
  'DRIVER_ERROR_REPEAT',
  'Driver and OS errors are remote-support first cases',
  'Repeated display driver reset, device manager error, Windows Update failure, driver install failure, nvlddmkm crash, or rollback available signals usually indicate a driver or OS repair path. If the PC can boot and Quick Assist can connect, remote support should inspect rollback, official driver install, device reset, and Windows Update retry before visit scheduling.',
  '드라이버 또는 OS 오류 반복 신호는 원격지원으로 먼저 확인하는 것이 적합합니다.',
  0.92,
  '{"keywords":["driver","display driver","nvlddmkm","device manager","windows update","rollback","드라이버","장치 관리자","윈도우 업데이트","블루스크린"],"remoteActions":["DRIVER_ROLLBACK","WINDOWS_UPDATE_CHECK","DEVICE_RESET"],"visitReasons":[]}'::jsonb
),
(
  'as-rag-remote-app-launcher',
  'REMOTE_APP_LAUNCHER',
  'TROUBLESHOOTING',
  'REMOTE_SUPPORT',
  'REMOTE_POSSIBLE',
  'APP_CRASH',
  'Application or launcher failures are usually remote-support cases',
  'Application crash, launcher crash, runtime missing, installer error, permission denied, cache corruption, and repairable app install failures usually fit a remote support workflow. Remote support can inspect runtime packages, permissions, app repair, cache cleanup, and reinstall guidance.',
  '앱 또는 런처 실행 오류는 원격지원으로 복구 가능성이 높습니다.',
  0.87,
  '{"keywords":["app crash","application crash","launcher","runtime missing","installer error","permission denied","앱 실행","런처","런타임","설치 오류","권한 오류"],"remoteActions":["APP_REPAIR","RUNTIME_INSTALL","CACHE_CLEANUP"],"visitReasons":[]}'::jsonb
),
(
  'as-rag-remote-storage-memory',
  'REMOTE_STORAGE_MEMORY',
  'TROUBLESHOOTING',
  'REMOTE_SUPPORT',
  'REMOTE_POSSIBLE',
  'STORAGE_MEMORY_PRESSURE',
  'Storage and memory pressure without disk failure are remote-support cases',
  'Low free space, memory pressure, pagefile spike, startup pressure, high disk active time without SMART critical or repeated I/O error usually fit remote support. Remote support can check temporary files, startup apps, pagefile configuration, and safe cleanup.',
  '저장공간 부족 또는 메모리 압박은 원격지원으로 점검하는 것이 적합합니다.',
  0.82,
  '{"keywords":["free space low","storage low","memory pressure","pagefile","disk active time","commit charge","저장공간","메모리","페이지파일","디스크 사용률","느림"],"remoteActions":["TEMP_FILE_CLEANUP","STARTUP_APP_REVIEW","PAGEFILE_CHECK"],"visitReasons":[]}'::jsonb
),
(
  'as-rag-remote-local-network',
  'REMOTE_LOCAL_NETWORK',
  'TROUBLESHOOTING',
  'REMOTE_SUPPORT',
  'REMOTE_POSSIBLE',
  'DNS_OR_ADAPTER_FAILURE',
  'Local network configuration failures are remote-support first cases',
  'DNS failure, gateway unreachable, adapter disabled, local NIC driver issue, or network configuration mismatch can be inspected remotely when the user can still access the web or Quick Assist. Remote support should check DNS reset, adapter reset, gateway, and NIC driver.',
  'DNS 또는 네트워크 어댑터 설정 문제는 원격지원으로 먼저 확인하는 것이 적합합니다.',
  0.80,
  '{"keywords":["dns failure","dns timeout","gateway unreachable","adapter disabled","nic driver","dns","게이트웨이","어댑터","네트워크","인터넷"],"remoteActions":["DNS_RESET","ADAPTER_RESET","NIC_DRIVER_CHECK"],"visitReasons":[]}'::jsonb
),
(
  'as-rag-visit-disk-failure',
  'VISIT_DISK_FAILURE',
  'TROUBLESHOOTING',
  'VISIT_SUPPORT',
  'REPAIR_OR_REPLACE',
  'DISK_FAILURE_SIGNAL',
  'SMART critical and repeated disk I/O errors require visit or replacement review',
  'SMART critical, predictive failure, bad block, repeated disk I/O error, filesystem error, disappearing drive, or storage device instability are hardware-risk signals. These should not be treated as a simple remote cleanup case. Visit support or repair/replacement review is recommended.',
  '디스크 장애 신호가 반복되어 방문 점검 또는 수리/교체 검토가 필요합니다.',
  0.96,
  '{"keywords":["smart critical","predictive failure","bad block","disk i/o","i/o error","filesystem error","drive disappeared","디스크 오류","배드블록","smart","저장장치 장애"],"remoteActions":[],"visitReasons":["SMART_CRITICAL","DISK_IO_ERROR_REPEAT"]}'::jsonb
),
(
  'as-rag-visit-whea-bsod',
  'VISIT_WHEA_BSOD',
  'TROUBLESHOOTING',
  'VISIT_SUPPORT',
  'VISIT_REQUIRED',
  'HARDWARE_CRASH_REPEAT',
  'Repeated WHEA or BSOD hardware errors require visit inspection',
  'Repeated WHEA logger event, bugcheck, BSOD, hardware error, memory hardware suspicion, or board-level crash signal indicates possible hardware instability. If repeated, visit support is recommended over simple self diagnosis.',
  'WHEA 또는 블루스크린 하드웨어 오류가 반복되어 방문 점검이 필요합니다.',
  0.94,
  '{"keywords":["whea","bugcheck","bsod","blue screen","hardware error","memory hardware","블루스크린","하드웨어 오류","메모리 오류"],"remoteActions":[],"visitReasons":["WHEA_ERROR_REPEAT","BSOD_REPEAT"]}'::jsonb
),
(
  'as-rag-visit-power-thermal',
  'VISIT_POWER_SHUTDOWN',
  'TROUBLESHOOTING',
  'VISIT_SUPPORT',
  'VISIT_REQUIRED',
  'POWER_OR_THERMAL_SHUTDOWN',
  'Power loss, fan failure, and thermal shutdown require visit inspection',
  'Kernel-Power 41, unexpected shutdown, power loss under load, thermal shutdown, thermal throttle with shutdown, fan rpm 0, or fan not spinning indicate power, cooling, or hardware inspection needs. Visit support is recommended.',
  '전원 꺼짐, 팬 이상, 열 차단 신호는 방문 점검이 필요합니다.',
  0.95,
  '{"keywords":["kernel-power","kernel power","event id 41","unexpected shutdown","power loss","thermal shutdown","thermal throttle","fan rpm 0","fan not spinning","전원 꺼짐","발열","팬","thermal"],"remoteActions":[],"visitReasons":["KERNEL_POWER_REPEAT","THERMAL_SHUTDOWN","FAN_RPM_ZERO"]}'::jsonb
),
(
  'as-rag-diagnosis-unclear',
  null,
  'SUPPORT_POLICY',
  'DIAGNOSIS_ONLY',
  'NEEDS_MORE_INFO',
  'INSUFFICIENT_EVIDENCE',
  'Unclear or weak log signals should start with diagnosis only',
  'When uploaded logs do not contain repeated rule signals or clear evidence for remote or visit support, the safe recommendation is diagnosis only. The user can provide more context or wait for admin review before requesting remote or visit support.',
  '명확한 반복 신호가 부족하면 우선 진단만 받기로 추가 확인하는 것이 적합합니다.',
  0.60,
  '{"keywords":["unknown","unclear","no signal","insufficient","정보 부족","불명확","추가 정보","진단"],"remoteActions":[],"visitReasons":[]}'::jsonb
),
(
  'as-rag-unsupported-scope',
  null,
  'SUPPORT_POLICY',
  'DIAGNOSIS_ONLY',
  'UNSUPPORTED',
  'UNSUPPORTED_SCOPE',
  'Out-of-scope issues should not be routed directly to remote or visit support',
  'Game-specific FPS tuning, overclocking stabilization, ISP or router hardware failure, peripheral or printer issues, data recovery, illegal software, and physical damage are outside the default PC Agent AS scope. These need diagnosis only or admin exception approval.',
  '지원 범위 밖 가능성이 있어 바로 원격/방문 신청보다 진단 또는 관리자 확인이 필요합니다.',
  0.58,
  '{"keywords":["fps tuning","overclock","isp","router","printer","peripheral","data recovery","illegal software","physical damage","오버클럭","공유기","프린터","주변기기","데이터 복구","물리 파손"],"remoteActions":[],"visitReasons":[]}'::jsonb
)
ON CONFLICT (source_id) DO UPDATE
SET symptom_type = EXCLUDED.symptom_type,
    source_type = EXCLUDED.source_type,
    recommended_service = EXCLUDED.recommended_service,
    support_decision = EXCLUDED.support_decision,
    reason_code = EXCLUDED.reason_code,
    title = EXCLUDED.title,
    chunk_text = EXCLUDED.chunk_text,
    summary = EXCLUDED.summary,
    score = EXCLUDED.score,
    metadata = EXCLUDED.metadata,
    active = true;
